[package]
name = "wasmprinter"
version = "0.2.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
repository = "https://github.com/bytecodealliance/wasmprinter"
homepage = "https://github.com/bytecodealliance/wasmprinter"
documentation = "https://docs.rs/wasmprinter"
description = """
Rust converter from the WebAssembly binary format to the text format.
"""
exclude = ['tests/wabt']

[workspace]
members = ['fuzz']

[dependencies]
anyhow = "1.0"
wasmparser = "0.50.0"

[dev-dependencies]
diff = "0.1"
getopts = "0.2"
rayon = "1.0"
tempfile = "3.0"
wast = "7.0.0"
wat = "1.0.8"

[[test]]
name = "wabt"
harness = false

[profile.release]
debug-assertions = true
overflow-checks = true
