[package]
name = "wast-libfuzzer"
version = "0.0.1"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
wasmprinter = { path = ".." }
libfuzzer-sys = "0.3.0"

[[bin]]
name = "print"
path = "fuzz_targets/print.rs"
